/* SINTAXE BASICA DE INSERÇÃO - INSERT INTO */

/* FORMA 01 - OMITINDO COLUNAS */

INSERT INTO CLIENTE VALUES(
    'JOAO',
    'M',
    'JOAO@GMAIL.COM',
    '988638273',
    '22923110',
    'MAIA LARCERDA - ESTACIO - RIO DE JANEIRO - RJ'
);

INSERT INTO CLIENTE VALUES(
    'CELIA',
    'F',
    'CELIA@GMAIL.COM',
    '541521456',
    '25078869',
    'RIACHUELO - CENTRO - RIO DE JANEIRO - RJ'
);

INSERT INTO CLIENTE VALUES(
    'JORGE',
    'M',
    NULL,
    '885755896',
    '58748895',
    'OSCAR CURY - BOM RETIRO - PATOS DE MINAS - MG'
);

/* FORMA 02 - COLOCANDO AS COLUNAS */

INSERT INTO CLIENTE(NOME,SEXO,ENDERECO,TELEFONE,CPF) VALUES('LILIAN','F','RIACHUELO - CENTRO - RIO DE JANEIRO - RJ','947785696','887774856');

/* FORMA 03 - INSERT COMPACTO - SOMENTE MYSQL */

INSERT INTO CLIENTE VALUES
    (
        'ANA',
        'F',
        'ANA@GLOBO.COM',
        '85548962',
        '548556985',
        'PRES ANTONIO CARLOS - CENTRO - SAO PAULO - SP'
    ),
    (
        'CARLA',
        'F',
        'CARLA@TERRATI.COM',
        '7745828',
        '66587458',
        'SAMUEL SILVA - CENTRO - BELO HORIZONTE - MG'
    );
