/* O COMANDO SELECT 

selecao, projecao e juncao*/

SELECT NOW() as DATA_HORA, 'JONATHAN SANTOS' AS PROFESSOR;

SELECT 'JONATHAN SANTOS'

SELECT 'BANCO DE DADOS'


/* ALIAS DE COLUNAS */

SELECT NOME, SEXO, EMAIL FROM CLIENTE;

SELECT NOME as CLIENTE, SEXO, EMAIL FROM CLIENTE;

SELECT NOME, SEXO, EMAIL, ENDERECO FROM CLIENTE;

SELECT EMAIL, SEXO,  ENDERECO, NOME FROM CLIENTE;

/* APENAS PARA FINS ACADEMICOS */

SELECT * FROM CLIENTE;