-- UTILIZANDO UPDATE PARA ATUALIZAR VALORES

SELECT 
    NOME,
    EMAIL
FROM CLIENTE;

-- MODO ERRADO (SEM WHERE)
UPDATE CLIENTE
SET EMAIL = 'LILIAN@HOTMAIL.COM';

-- MODO CORRETO
UPDATE CLIENTE
SET EMAIL = 'LILIAN@GMAIL.COM'
WHERE NOME = 'LILIAN';