-- DELETANDO REGISTROS COM A CLUASA DELETE

-- MODO ERRADO SEM WHERE
DELETE FROM CLIENTE;

-- DICA: ANTES DE DELETAR, CONTAR QUANTOS REGISTROS A TABELA TEM

-- TOTAL 6
SELECT COUNT(*) 
FROM CLIENTE;

-- TOTAL DE ITENS A SEREM DELETADOS = 1
SELECT COUNT(*)
FROM CLIENTE
WHERE NOME = 'ANA';

DELETE FROM CLIENTE
WHERE NOME = 'ANA';


-- PROVA REAL: PRIMEIRO COUNT - QTD DE ITENS A SEREM DELETADOS = 
SELECT COUNT(*) 
FROM CLIENTE;


INSERT INTO CLIENTE VALUES(
    'CARLA',
    'F',
    'C.LOPES@UOL.COM',
    45638854,
    '4575-0048',
    'RUA COPPER LEAF - WILLIAMSBURG - KITCHENER'
);

-- CONFIRMANDO QUAL REGISTRO DEVE SER EXCLUIDO

SELECT * FROM CLIENTE
WHERE NOME = 'CARLA'
AND EMAIL = 'CARLA@TERRATI.COM';

DELETE FROM CLIENTE
WHERE NOME = 'CARLA'
AND EMAIL = 'CARLA@TERRATI.COM';

