/* SELECAO, PROJECAO E JUNCAO */

/* PROJECAO -> É TUDO QUE VOCE QUER VER NA TELA */

    USE CLIENTE;

    SELECT NOW() AS DATA_ATUAL;

    SELECT 2 + 2 AS SOMA;

    SELECT 2 + 2 AS SOMA, NOME, NOW()
    FROM CLIENTE;


/* SELECAO -> É UM SUBCONJUNTO DO CONJUNTO TOTAL DE REGISTROS DE UMA TABELA
A CLAUSULA DE SELECAO É O WHERE
*/

    SELECT NOME, SEXO, EMAIL /* PROJECAO */
    FROM CLIENTE /* ORIGEM */
    WHERE SEXO = 'F'; /* SELECAO */

    SELECT NUMERO /* PROJECAO */
    FROM TELEFONE /* ORIGEM */
    WHERE TIPO = 'CEL'; /* SELECAO */

/* JUNCAO -> JOIN */

    SELECT 
        NOME, 
        EMAIL,
        IDCLIENTE
    FROM CLIENTE;

    SELECT 
        ID_CLIENTE, 
        BAIRRO,
        CIDADE
    FROM ENDERECO;

    -- NOME, SEXO, BAIRRO, CIDADE 

    SELECT -- PROJECAO
        NOME,
        SEXO,
        BAIRRO,
        CIDADE 
    FROM CLIENTE -- ORIGEM
        INNER JOIN ENDERECO -- JUNCAO
        ON IDCLIENTE = ID_CLIENTE;


    SELECT -- PROJECAO
        NOME,
        SEXO,
        BAIRRO,
        CIDADE 
    FROM CLIENTE -- ORIGEM
        INNER JOIN ENDERECO -- JUNCAO
        ON IDCLIENTE = ID_CLIENTE
    WHERE SEXO = 'F'; -- SELECAO
    
    -- NOME, SEXO, EMAIL, TIPO, NUMERO 

    SELECT
        NOME,
        SEXO,
        EMAIL,
        TIPO,
        NUMERO 
    FROM CLIENTE 
        INNER JOIN TELEFONE 
        ON IDCLIENTE = ID_CLIENTE;
    

    -- NOME, SEXO, BAIRRO, CIDADE, TIPO, NUMERO

    SELECT 
        CLIENTE.NOME,
        CLIENTE.SEXO,
        ENDERECO.BAIRRO,
        ENDERECO.CIDADE,
        TELEFONE.TIPO,
        TELEFONE.NUMERO 
    FROM CLIENTE 
        INNER JOIN ENDERECO
        ON  CLIENTE.IDCLIENTE =  ENDERECO.ID_CLIENTE
        INNER JOIN TELEFONE
        ON  CLIENTE.IDCLIENTE = TELEFONE.ID_CLIENTE;

    -- obs: NO CASO ACIMA, FOI NECESSARIO IDENTIFICAR DE QUAL TABELA DEVERIVAVA A COLUNA, DEVIDO A AMBUIGUIDADE (NOMES DE COLUNAS IGUAIS EM TABELAS DIFERENTES). O NOME DISSO É PONTEIRAMENTO/PONTEIRO, ISSO AJUDA MTO NA PERFORMANCE DO BANCO, NA HORA QUE ELE BUSCA A ORIGEM.