-- DML - DATA MANIPULATION LANGUAGE

CREATE TABLE PRODUTO(
    IDPRODUTO INT PRIMARY KEY AUTO_INCREMENT,
    NOME_PRODUTO VARCHAR(30) NOT NULL,
    PRECO INT, 
    FRETE FLOAT (10,2) NOT NULL 
);

-- ALTER TABLE 

-- ALTERANDO O NOME DE UMA COLUNA - CHANGE 

-- alterando o nome e inserindo o "not null"
ALTER TABLE PRODUTO 
CHANGE PRECO VALOR_UNITARIO INT NOT NULL;

DESC PRODUTO;

--alterando/removendo a clausula not null. obs: é necessário colocar o "novo" nome, mesmo que vc não queira alterar (repetir).
ALTER TABLE PRODUTO 
CHANGE VALOR_UNITARIO VALOR_UNITARIO INT;


--MODIFY 

--alterando o tipo, não é necessário repetir o nome.
ALTER TABLE PRODUTO 
MODIFY VALOR_UNITARIO VARCHAR(50) NOT NULL;


-- ADICIONANDO COLUNAS 

ALTER TABLE PRODUTO
ADD PESO FLOAT(10,2) NOT NULL;

-- APAGANDO UMA COLUNA

ALTER TABLE PRODUTO
DROP COLUMN PESO;

-- ADICIONANDO UMA COLUNA NA ORDEM/POSICAO ESPECIFICA

ALTER TABLE PRODUTO 
ADD COLUMN PESO FLOAT(10,2) NOT NULL
AFTER NOME_PRODUTO;

--adicionando na primeira posicao 

ALTER TABLE PRODUTO 
ADD COLUMN PESO FLOAT(10,2) NOT NULL 
FIRST;