-- ORDER BY

CREATE TABLE ALUNOS(
    NUMERO INT,
    NOME VARCHAR(30)
);

INSERT INTO ALUNOS VALUES(1, 'JOAO');
INSERT INTO ALUNOS VALUES(1, 'MARIA');
INSERT INTO ALUNOS VALUES(2, 'ZOE');
INSERT INTO ALUNOS VALUES(2, 'ANDRE');
INSERT INTO ALUNOS VALUES(3, 'CLARA');
INSERT INTO ALUNOS VALUES(1, 'CLARA');
INSERT INTO ALUNOS VALUES(4, 'MAFRA');
INSERT INTO ALUNOS VALUES(5, 'JANAINA');
INSERT INTO ALUNOS VALUES(1, 'JANAINA');
INSERT INTO ALUNOS VALUES(3, 'MARCELO');
INSERT INTO ALUNOS VALUES(4, 'GIOVANI');
INSERT INTO ALUNOS VALUES(5, 'ANTONIO');
INSERT INTO ALUNOS VALUES(6, 'ANA');
INSERT INTO ALUNOS VALUES(6, 'VIVIANE');

SELECT * FROM ALUNOS
ORDER BY NUMERO;

SELECT * FROM ALUNOS
ORDER BY 1;

-- ORDENANDO PELO NUMERO/INDICE DA COLUNA

SELECT * FROM ALUNOS
ORDER BY 2;

-- ORDENANDO POR MAIS DE UMA COLUNA 

SELECT * FROM ALUNOS
ORDER BY NUMERO, NOME;

SELECT * FROM ALUNOS
ORDER BY 1, 2;

-- ORDER BY DESC / ASC 

SELECT * FROM ALUNOS
ORDER BY NUMERO DESC;

SELECT * FROM ALUNOS
ORDER BY NUMERO DESC, NOME DESC;

-- ORDENANDO COM JOINS

SELECT 
    C.nome,
    IFNULL(C.email, '********') as Email,
    T.numero,
    E.estado
FROM CLIENTE C
INNER JOIN ENDERECO E 
ON C.idcliente = E.id_cliente
INNER JOIN TELEFONE T
ON C.idcliente = T.id_cliente
ORDER BY C.nome;

-- ORDENANDO VIEWS 

SELECT * FROM V_RELATORIO
ORDER BY 1;