-- DESAFIO: QUAL VENDEDOR VENDEU MENOS EM MARCO E O SEU NOME 

-- Teste sem sub
SELECT 
    NOME,
    MARCO
FROM VENDEDORES
ORDER BY MARCO
LIMIT 1;

-- Com sub no where
SELECT 
    NOME,
    MARCO
FROM VENDEDORES
WHERE MARCO = (SELECT MIN(MARCO) FROM VENDEDORES);


SELECT 
    NOME
FROM (SELECT MIN(MARCO) FROM VENDEDORES);
