CREATE TABLE tabela(
    coluna1 VARCHAR(30),
    coluna2 VARCHAR(30),
    coluna3 VARCHAR(30)
);

-- ADICINANDO UMA PK 
-- obs: fazendo dessa forma, não é possível utilizar o auto increment

ALTER TABLE tabela
ADD PRIMARY KEY (coluna1);

-- ADICIONANDO UMA COLUNA SEM POSICAO, ULTIMA POSICAO (AUT)

ALTER TABLE tabela 
ADD coluna varchar(30);

ALTER TABLE tabela 
ADD coluna100 INT;

-- ESCOLHENDO A POSICAO 

ALTER TABLE tabela
ADD COLUMN coluna4 VARCHAR(30) NOT NULL UNIQUE
AFTER coluna3;

-- MODIFICANDO O TIPO DE UM CAMPO

ALTER TABLE tabela 
MODIFY coluna2 DATE NOT NULL; 

-- RENOMEANDO UMA TABELA 
ALTER TABLE tabela
RENAME PESSOA;

CREATE TABLE CLUBE(
    IDCLUBE INT PRIMARY KEY AUTO_INCREMENT,
    CLUBE VARCHAR(30),
    ID_PESSOA VARCHAR(30)
);

-- ADICIONANDO UMA FOREIGN KEY
ALTER TABLE CLUBE 
ADD FOREIGN KEY(ID_PESSOA)
REFERENCES PESSOA(COLUNA1);

-- VERIFICAR AS CHAVES 

SHOW CREATE TABLE CLUBE;